### ISSUE TITLE
API disk usage

### ISSUE THREAD

**Issue by dgasmith** [lpwgroup/torsiondrive#20]
I noted that the API uses a significant amount of disk IO from writing/reading many files and does not appear to fully clean itself up after completion. It would be good if the API could completely clean up all temporary files and folders when a function completes.

As the current plan is to run these on the server itself or AWS lambda this amount of possible IO could be problematic as we may be calling the crank API multiple times per second (each call for a different job). As the database IO will already be quite heavy, it would be great if we could remove this contention and keep this entirely in memory.

The first point is needed for a first pass at the DB project while the second will be required when we thinking about computing a large number of torsion scans.

**Comment by yudongqiu** [comment]
The first point leads to deleting the `opt_tmp` folder, which is trivial, and I can make that change first.

For the second point, I understand why it's preferred to keep everything in memory. This issue lingers but haven't been solved because the crank cache structure is built to be folders on the disk, which is the native way to recover lost progress after a hardware failure or manual interupt happens. I will try to get around that in crankAPI after the recent PR is merged (otherwise I expect there will be quite a lot of conflicts).

**Comment by leeping** [comment]
I wonder if we could create a virtual in-memory file system when running in API mode, perhaps using a package like this: https://github.com/PyFilesystem/pyfilesystem2

This could reduce the amount of code duplication when Crank is running in API mode vs. application mode.

**Comment by yudongqiu** [comment]
@leeping Thanks for that suggestion. I was able to make the crankAPI runs completely in memory, by using a child class of DihedralScanner and overwriting methods that creates folders. aaf652f6aaf4a8d8a2bc399aec47a3e26fee89b0
