### ISSUE TITLE
running torsiondrive in parallel

### ISSUE THREAD

**Issue by qasimpars** [lpwgroup/torsiondrive#40]
Hi,

Is that possible to run `torsiondrive-launch` in parallel? If yes, how? For instance; these flags
`--nt=16`, `-nt=16` or `-n=16` didn't work for that.

Thanks in advance.

**Comment by yudongqiu** [comment]
@qasimpars Thanks for the feedback.

`torsiondrive-launch` in default mode runs one constrained optimization at a time. It is suggested to use the settings for QM programs to let them run in parallel. For example, adding `set_num_threads(nthread)` in Psi4 input file [ref](http://www.psicode.org/psi4manual/master/external.html)

I found that QChem only support command line options `-np` or `-nt` to specify parallelization, so I will consider adding a command line option to pass to the QChem interface.

Meanwhile `torsiondrive` also support distributed computing, by using the `cctools.work_queue` library. It can be installed by `devtools/travis-ci/install-cctools.sh` [link](https://github.com/lpwgroup/torsiondrive/blob/master/devtools/travis-ci/install-cctools.sh)

Once installed, using `torsiondrive-launch --wq PORT` will create a "host", and calling `cctools/bin/work_queue_worker HOST PORT` locally or on a remote computing node will create a worker for running the constrained optimizations.

Hope this helps!

**Comment by qasimpars** [comment]
@yudongqiu Thanks for your response.

I did as you said (by adding `set_num_threads(24)` in Psi4 input file) but it still works very slowly. I ran the following input file 6 days ago but it hasn't finished yet. Do you think that is something expected?
Here is my input file (**input.dat**):
```
memory 2 GB

molecule {
  0 1
  C  0.281   0.772   0.721
  O  -0.311   2.003   0.362
  H  -0.070   0.470   1.720
  H  1.371   0.871   0.723
  H  -0.011   0.011  -0.001
  H  0.021   2.231  -0.521
symmetry c1
}

set {
  basis aug-cc-pvtz
}
set_num_threads(24)
optimize('ccsd(t)')
gradient('ccsd(t)')
```
Here is the input file of dihedrals (**dihedrals.txt**):
```
# dihedral definition by atom indices starting from 0
# i     j     k     l
  3     1     2     6
  4     1     2     6
  5     1     2     6
```
And here is the command used to run the program: `torsiondrive-launch input.dat dihedrals.txt `

**Comment by yudongqiu** [comment]
@qasimpars Wow you're running the most expensive torsiondrive scan I've seen. 

#### For the scan setting
1. You're running a 3-D scan. With the default grid spacing of `15`, it's 24 grid points in each dimension, which totals at `24 x 24 x 24 = 13824` grid points. In the 3-D scan each grid point has 6 neighbors, therefore the total number of constrained optimizations are at least `13824 x 6 = 82944`, and could be more.
2. Assuming each constrained optimization takes 20 iterations, it becomes a total `82944 x 20 = 1658880` iterations of optimization. Because a gradient evaluation is needed for each iteration, you can use the printed time cost of one Psi4 gradient times `1658880` to be an estimate of the total running time of the entire torsiondrive scan.
- For a scan at this scale, I would highly recommend using the distributed computing feature, by specifying `--wq_port PORT` argument. You will need to install `cctools` to use that. This script could help: https://github.com/lpwgroup/torsiondrive/blob/master/devtools/travis-ci/install-cctools.sh

#### For the Psi4 Input
1. You're running at the CCSD(T)/cc-pVTZ level of theory. For a scan at this scale, I could recommend using a lower level of theory, as the geometry optimization is not extremely sensitive to the level of theory. More accurate energies could be obtained by running single point calculations on converged structure for each grid point, there will be "only" `13824` of single-point calculations needed.
2. Quantum calculations in general does not benefit linearly from using a large number of cores. Using 24 threads may actually be slower than 16, which might then be only a bit faster than 8. I would suggest running a benchmark on single gradients to decide the best number of threads to use. If I'm running the calculation in a distributed system, for a fixed number of total CPUs I would use a lower number of threads for each job, because the 3-D scan has so many jobs to run in parallel. For example if I have a total of 320 CPUs, `80 jobs x 4 CPU each` should finish faster than `20 jobs x 16 CPU each`.
3. Your input file shows that
    ```
    optimize('ccsd(t)')
    gradient('ccsd(t)')
    ```
    which is **wrong**. In this setting Psi4 will optimize the geometry then compute the gradient, causing the gradient to not be the one geomeTRIC wants. You should remove the `optimize('ccsd(t)')` line.
- In general, I would pick a suitable level of theory and run a single Psi4 gradient job, then use that time cost to estimate the total time cost of the torsiondrive scan.

Hope this helps!
